version: "3.7"

services:
  database:
    image: postgres
    container_name: database_eliminatorias
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=abmex
      - POSTGRES_DB=eliminatorias
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: sistema-eliminatorias
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
